---
title: "About Me"
toc: true
---

# Introduction

My name is Yunyi Ru. I am a 1st year Ph.D. student from the [PULSe Interdisciplinary Life Sciences Program](https://www.purdue.edu/gradschool/pulse/) at [Purdue University](https://www.purdue.edu/). 

## Why Blogging

I made this blog to share... 

- useful biological science-related contents

- random bioinfo/CS projects

::: column-margin
**Recent Highlights**

I worked with my friend Juanyu to create an interactive dashboard which explores the relationship between *environmental parameters* and *respiratory virus-associated hospitalization rates*. [**Check it out!**](https://yunyi-ru.github.io/quarto-blog/projects/RESPweather_dashboard/)
:::

## Fun Facts About Me

Outside of lab, I enjoy digital painting, [birdwatching](https://yunyi-ru.github.io/quarto-blog/projects/all_about_birding/), and [discovering interesting music](https://yunyi-ru.github.io/quarto-blog/projects/lyric_analysis/).

My name Yunyi writes as 云衣 in Chinese - it comes from a poem by Li Bai, a poet my mom loves:

> *云想衣裳花想容，春风拂槛露华浓。The clouds resemble her dress, and the flowers mirror her beauty. In the spring breeze brushing against the balcony, the dewdrops gleam richly. (English Translation provided by ChatGPT)*

------------------------------------------------------------------------

# Résumé

## Education

**Purdue University** \| West Lafayette, IN \| PhD Student ???

**Johns Hopkins University** \| Baltimore, MD \| ScM '25, Molecular Microbiology and Immunology

**Duke Kunshan University/Duke University** \| Kunshan, China/Durham, NC \| BS '23, Cell and Molecular Biology (Dual Degree)

## Experience

#### Research

[**The Pekosz Lab**](https://pekoszlab.com/)**, Johns Hopkins University** \| *Graduate Student* \| Oct '23 - May '25

-   Characterized respiratory syncytial virus using various molecular biology and genetics methods.

[**The Lin Lab**](https://yajuanlin.github.io/)**, Duke Kunshan University** \| *Undergraduate Student* \| Oct '21 - May '23

-   Monitored and analyzed changes in antibiotic resistance gene prevalence in a local shallow lake over the year.

#### Others

[**R3ISE Center**](https://publichealth.jhu.edu/the-r3-center-for-innovation-in-science-education)**, Johns Hopkins University** \| *Research Assistant* \| Oct '23 - Oct '24

-   Initiated the 'R3 Read Today' project on responsible scientific practices for science communication on [X](https://twitter.com/R3_JHSPH) and [Instagram](https://www.instagram.com/r3_jhsph/).

[**iGEM 2022**](https://2022.igem.wiki/dku/index.html)**, Duke Kunshan University** \| *Team Leader* \| Dec '21 - Oct '22

-   Designed an engineered bacteria strain by molecular cloning and protein expression.

**HOB Biotech Group Suzhou Co., Ltd** \| *R&D Intern* \| Jul - Aug '21

**Crystal Pharmatech Co., Ltd** \| *R&D Intern* \| May - Jun '20
